// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyi5z_Id5MwAZ6BxlcBS50ukFH-4VBDo',
    appId: '1:751435728676:web:29d7cce26254ced69855b1',
    messagingSenderId: '751435728676',
    projectId: 'vn-todo-calendar',
    authDomain: 'vn-todo-calendar.firebaseapp.com',
    storageBucket: 'vn-todo-calendar.appspot.com',
    measurementId: 'G-9C43ZQG79S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlF0mrKb3yOYP6ngyhiu01rJ4kjbRugQs',
    appId: '1:751435728676:android:f8ce91221fd590e89855b1',
    messagingSenderId: '751435728676',
    projectId: 'vn-todo-calendar',
    storageBucket: 'vn-todo-calendar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIoto-4YoAdL45eTIMynH-00aMzENCN0c',
    appId: '1:751435728676:ios:89391509780d17979855b1',
    messagingSenderId: '751435728676',
    projectId: 'vn-todo-calendar',
    storageBucket: 'vn-todo-calendar.appspot.com',
    iosBundleId: 'com.vn.vical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIoto-4YoAdL45eTIMynH-00aMzENCN0c',
    appId: '1:751435728676:ios:ba04fe1a732f1e989855b1',
    messagingSenderId: '751435728676',
    projectId: 'vn-todo-calendar',
    storageBucket: 'vn-todo-calendar.appspot.com',
    iosBundleId: 'com.vn.vical.RunnerTests',
  );
}
